---

- name: Define the path to the ssh keys
  set_fact:
    key_path: "{{ role_path }}/files/id_rsa"
    pub_key_path: "{{ role_path }}/files/id_rsa.pub"

- name: Create local pair of private/public keys (priv key must be added to Gitlab, or whereever you want to connect from)
  #local_action:
  #  module: openssh_keypair
  openssh_keypair:
    type: rsa
    size: 4096
    comment: ansible_local_key
    path: "{{ key_path }}"
    state: present
  delegate_to: localhost

- name: Add the public key that we have just generated to the local user on the controller machine/node.
  #local_action:
  #  module: authorized_key
  authorized_key:
    user: "{{ controller_enabled_user }}"
    state: present
    exclusive: no
    key_options: "{{ authorized_key_key_options }}"
    key: "{{ lookup('file', pub_key_path) }}"
  delegate_to: localhost
  when: controller_enabled_user is not empty
